# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
	config.vm.synced_folder "share", "/share"
	config.vm.hostname = "richie1.local"
	config.vm.box = "chad-thompson/ubuntu-trusty64-gui"
	config.vm.network :public_network, ip: "192.168.1.110"
	config.vm.provision :shell, path: "bootstrap.sh"
	config.vm.provider :virtualbox do |master|
		master.gui = true
		master.name = "richie1"
		master.memory = 4096
		master.cpus = 2
	end
end